### ISSUE TITLE
context/should make rails test output not correct.

### ISSUE THREAD

**Issue by zw963** [thoughtbot/shoulda-context#56]
Rails 5 give us a new function which can output can rerunable command with
following format:

``` rb
bin/rails test the/path/of/failed/test/file
```

But, use with shoulda, we always got the following content.

``` rb
bin/rails test /home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/shoulda-context-1.2.1/lib/shoulda/context/context.rb:399
```

**Comment by mcmire** [comment]
Hey, just going over old issues and seeing whether they are relevant or not. I didn't even know this was a thing in Rails 5, but I found where in the Rails source that this gets added:

* https://github.com/rails/rails/blob/4d9ba8b50b0ff01d19ff786aa64c9da0fb31aa7e/railties/lib/minitest/rails_plugin.rb (Minitest will load this file automatically)
* https://github.com/rails/rails/blob/4d9ba8b50b0ff01d19ff786aa64c9da0fb31aa7e/railties/lib/rails/test_unit/reporter.rb#L71-L79

Essentially, though, Rails looks at the source location of the test method to know what to print out. The issue here is that since Shoulda Context adds the test methods from within the gem itself, the source location of the method is shoulda/context/context.rb instead of the test file. There's really not a great way to fix this other than rewriting how Shoulda Context fundamentally works. I am planning on reimplementing Shoulda Context in terms of Minitest::Spec anyway, but I'm not sure how long that's going to take. I'll keep this issue open in the meantime.

**Comment by fsateler** [comment]
This was fixed on 7d496b55a89bce3f62fd7ced3dbd9c3a6fe99e1d (ie, 1.2.2 does not have the problem), but the fix was lost on 9b791b4f26e49930f59a49c5b2acff67aabcc15f .

**Comment by mcmire** [comment]
@fsateler Oh I didn't realize that's what that was doing 🤦‍♂️ I'll change this back.

**Comment by mcmire** [comment]
This should be fixed. ^
